### PR TITLE
The Next Web Project

### PR DESCRIPTION
**Pull request by yigitm**
This project consists of building a clone of [THE NEXT WEB](https://thenextweb.com/) site.

Main Features:

- This project covers the following HTML and CSS3 concepts
- Fixed, relative, absolute positioning and flex
- Responsive Design by using media queries

Thank you for your time & support.

### CODE REVIEW

**Comment by santiago-dev96** [comment]
# Pull Request under review by @santiago-rodrig (TSE)

**Review by santiago-dev96 — CHANGES_REQUESTED** [review]
# Changes required

1. The TNW logo does not appear at the leftmost part of the navigation bar on medium screens
**Original**

Screen Shot 2020-06-03 at 8 43 22 AM

**Yours**

Screen Shot 2020-06-03 at 8 43 29 AM

2. The image quality of the TNW logo on small screens is sloppy

Screen Shot 2020-06-03 at 8 45 29 AM

3. You are not using a gradient background for the main article in large screens

**Original**

Screen Shot 2020-06-03 at 8 47 38 AM

**Yours**

Screen Shot 2020-06-03 at 8 47 31 AM

4. The TNW logo should disappear from the main article in medium screens

Screen Shot 2020-06-03 at 8 48 53 AM

## What to do now?

Implement the required changes and submit another CRR (Code Review Request).

## How can you reach out to me?

I'm available in slack as **srodrig**, happy coding! :wave:

**Comment by voscarmv** [comment]
# Pull Request Under Review by Oscar Mier (TSE) 👨‍💻 🐦

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Changes required, team! ⛔  🧰 🔨 🔧 

## The following changes are required before you may continue...

- ### There is overlapping on the Small display, please fix it before re-submitting!
image

- ### Your footer is missing the TNW logo. Please fix your footer to make it more similar to the original! 🦶 = 🦶 


### **Original**


image


### **Yours**


image

- ### Your latest news section on the Medium Display shows only two columns. It must show **three** columns, and the titles must be under the images, like the original.


### **Original**


image


### **Yours**


image

- ### Your Latest Funding section on Medium Display shows **Two** columns. Please fix it to show 3 columns like the original:


### **Original**


image


### **Yours**


image

- ### Your Latest Deals section shows **Two** columns on  Medium Display and it should show 3 columns:


### **Original**


image

### **Yours**

image

# Please apply these changes and submit for re-review! 😄 👍 

### Comments or questions? Feel free to contact me! www.twitter.com/voscarmv www.linkedin.com/in/oscar-mier 🧑‍💻 🗨️ 🧑‍💻 

# Happy Coding! 💻 🖱️ 🔢 🧠

**Comment by voscarmv** [comment]
# Important Reminder 🧠 ❗ 

### Please remember to always update your **Live Demo Link** on every re-submission!

# Good luck! 🤞 🍀

**Comment by BrittanyBlake** [comment]
### Pull Request Under Review by Brittany Blake (TSE) 👩🏾‍💻

**Review by BrittanyBlake — CHANGES_REQUESTED** [review]
### Status: Changes Requested ♻️ 
****
### Hi @yigitm and @ClaytonSiby 👋 👋 
Amazing job on your project so far! You have done a great job implementing the requested changes and your project looks really good so far! 👍 However, the following issues need to be fixed before you can move forward 👩🏾‍💻 ⬇️
****
### Navigation 

- [ ] As pointed out by the first TSE, the TNW logo on the small screen could be improved. The height shrinks on the small screen and there should be no gap between it and the element below. Please compare with the original page and fix this:
Your clone 👇 
Screen Shot 2020-06-05 at 8 24 16 AM
The original page 👇 
Screen Shot 2020-06-05 at 8 24 28 AM

### Latest funding

- [ ] On the small screen, the links should not be underlined. Please fix this.
Your clone 👇 
Screen Shot 2020-06-05 at 8 26 30 AM
The Original page 👇
Screen Shot 2020-06-05 at 8 26 41 AM
[optional]: The font size appears to be smaller than that of the original page.


### Optional! (Please note that anything marked as optional is not required but would be nice to implement 😄 )

- [ ] The font in many areas of your page appears to be significantly smaller than that of the clone. In some cases, this can make it hard to read. I have given some examples below, but these are not the only areas that have this issue:
Your clone 👇 
Screen Shot 2020-06-05 at 8 23 52 AM
The original page 👇 
Screen Shot 2020-06-05 at 8 24 01 AM
Your clone 👇 
Screen Shot 2020-06-05 at 8 25 44 AM
The original page 👇 
Screen Shot 2020-06-05 at 8 25 51 AM

****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

God luck & Happy Coding! 🍀 😄 

P.S.
If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake).

**Comment by peterrobert** [comment]
### PULL REQUEST UNDER REVIEW BY PETER ROBERT (TSE)

**Review by peterrobert — APPROVED** [review]
### APPROVED :100: :+1: :1st_place_medal: 

Very impressive work :clap: You have made all the changes requested. :1st_place_medal:  Your pull request looks professional :+1:  great commit messages :+1:  stickler validations are all passing :+1:  

You left me no choice but to approve your project **very great work** :+1: 

On to the next project. Remember to merge your branch to master and submit the project completion form
### HAPPY CODING

**Pull request merged**
